ELIFE-ASU/Neet

setup.py
The neet package provides several network models and algorithms
to explore network dynamics.
=> Create the neet package

neet/boolean/wtnetwork.py, test/test_boolean.py
This commit addresses issue #11, **but does not close it**. We still need to implement single-node update for cellular automata.
=> Add single-node update for WTNetworks

neet/landscape.py, requirements.txt, setup.py, test/test_landscape.py
=> Add transition graph and attractor functionality to landscape module

docs/source/landscape.rst, neet/landscape.py, test/test_landscape.py
Add landscape.basins and documentation!
This contributes to issue #15
=> Attractors

neet/boolean/wtnetwork.py, test/test_boolean.py
added ability to initialize WTNetworks using an int, which makes a completely disconnected network with the number of nodes equal to `weights`. Added tests for this.
=> added ability to init wtnetworks with an int, added tests for this

neet/boolean/__init__.py, neet/boolean/logicnetwork.py, neet/sensitivity.py, neet/statespace.py, test/test_interfaces.py, test/test_logic.py, test/test_sensitivity.py
LogicNetwork can now update net state with a truth table. `classmethod` attribute `read_table` remains to be implemented.
=> Added LogicNetwork class

neet/synchronous.py, test/test_synchronous.py
I had a sudden urge to code, so I implemented the basin entropy.  Woo :)
This contributes to #15
=> Basin entropy

.gitignore, neet/boolean/data/myeloid-logic_table.txt, neet/boolean/examples.py, neet/boolean/logicnetwork.py, test/test_logic.py, test/test_logic_examples.py
Added myeloid logic table data in `data` folder. Added a few test cases for the new function and example data.
=> Implemented `LogicNetwork.read`. 

neet/automata.py, neet/boolean/wtnetwork.py, test/test_automata.py, test/test_boolean.py
This pull request implements value fixing for the `WTNetwork` and `ECA` classes as well as state pinning for `ECA` (`WTNetwork` already has that!).
This request contributes to #18
=> Value Fixing and State Pinning

neet/boolean/randomnet.py
A quick and dirty modification to the original implementation. New proposed API still in work.
=> Add `fix_external` to randomization functions

test/test_randomnet.py
Adds some basic tests for fixed-structure, fixed-in-degree, and fixed-mean-degree random networks.
=> Add basic tests for randomnet

neet/boolean/randomnet.py
A dumb but easy way to make irreducible networks quickly is to check each node as you're going to see if it's irreducible, and try again if it's not.
=> quick fix to make irreducible networks quickly

.travis.yml
This commit sets up code coverage checks via Travis CI and [CodeCove](https://codecov.io).
To see an example of a code coverage report: https://codecov.io/gh/dglmoore/Neet/branch/code-coverage.
=> Setup code coverage

neet/boolean/wtnetwork.py, test/test_boolean.py
=> add tests for non-split threshold thetas

neet/interfaces.py, test/test_interfaces.py
=> Improved test codes

neet/boolean/conv.py, test/test_conv.py
Ensure that wt_to_logic raises an error if net is not a WTNetwork
=> Fix coverage of wt_to_logic

.flake8, docs/source/conf.py, neet/automata/__init__.py, neet/automata/eca.py, neet/boolean/__init__.py, neet/boolean/conv.py, neet/boolean/randomnet.py, neet/sensitivity.py, neet/synchronous.py, test/test_canary.py, test/test_information.py, test/test_logic_examples.py, test/test_randomnet.py, test/test_reca.py, test/test_synchronous.py
Cleanup formatting with flake8 and autopep8.
=> Satisfy flake8 and reformat with autopep8

LICENSE, README.md, docs/source/conf.py, docs/source/index.rst
=> Add Codecov Badges and Fix Copyright

neet/boolean/sensitivity.py, neet/information.py, neet/network.py, neet/synchronous.py, test/test_synchronous.py
`Landscape` is now a `LandscapeMixin`. This addresses #147. 
`Landscape` also stores its data in another class, `LandscapeData` for easy access.
Tests have been updated, but documentation still needs to be updated. Will update when everything looks good enough to merge.
=> Landscape data

neet/boolean/randomnet.py
=> Change "fixed" to "fixed-structure"
