- LICENSE
- neet/__init__.py
- setup.py
The default license file, generated by GitHub, did not include an
attribution. We added attribution to ELIFE and updated the source
file copyright headers to reflect this change.
> Update Licensing Information

- neet/boolean/wtnetwork.py
- test/test_boolean.py
This commit extends the `update` and `_unsafe_update` methods of `WTNetworks` with an optional argument `pin`. The argument provided should be a sequence (likely a list or NumPy array) of indices to "pin" to their current values. This is, effectively, the same as updating the state and then resetting the nodes specified by `pin` to their previous state.
This pull request partially addresses issue #18.
> Implement basic state pinning for WTNetworks

- setup.py
Add example files as `package_data`. The example data files in neet.boolean were not being installed. We added those files to the setup script.
> Include data files for boolean networks in installation

- neet/sensitivity.py
- test/test_sensitivity.py
The previous sensitivity calculation was incorrect and is now fixed.  
The old way interpreted a boolean function as having an output that is an entire binary vector, and counted the number of hamming neighbors that produced output that was different in any way.  The definition in Shmulevich and Kauffman's paper was instead intended for functions with a single binary output, corresponding to each node in our networks.  
So we instead want the average sensitivity over nodes, which corresponds to summing the hamming distances (between the original output network state and the output network state starting from hamming neighbors) and dividing by the number of nodes.
This is all still implemented rather naively and could likely be made much faster.
This would close issue #62 .
> Sensitivity fix

- neet/asynchronous.py
- neet/statespace.py
- neet/synchronous.py
We have made several performance improvements which have reduced the runtime for the test suite by approximately 54%. The greatest improvement comes from the use of `synchronous.transitions` instead of `synchronous.trajectory` within `synchronous.timeseries`. This allows us to use the transitions array as a lookup table and thus only compute the state updates once for each state in the network.
> Improved Performance

- neet/synchronous.py
- test/test_synchronous.py
We reimplemented `synchronous.attractors` to avoid using the `networkx` at any stage. This reduces the memory usage by around an order of magnitude for reasonably sized networks (and only gets better as the size of the network increases), and improves the runtime performance about around 67%.
> Improve attractors performance

- neet/boolean/examples.py
- neet/boolean/logicnetwork.py
- neet/boolean/wtnetwork.py
- test/test_boolean.py
- test/test_boolean_examples.py
- test/test_logic.py
Adds a metadata dictionary to all boolean networks.
I added some example metadata to the networks in neet.boolean.examples.
Still to do: 
(1) We should add citation metadata for all the example networks.  (I think I got the right one for the p53 network, but someone should check.) 
(2) When constructing random networks in randomnet.py, we can add metadata that keeps track of what randomization was used.  This could/should include the random seed used (though we don't have a way of setting this yet.)
This contributes to issue #66
> Add metadata for boolean networks

- docs/source/synchronous.rst
- neet/statespace.py
- neet/synchronous.py
- test/test_statespace.py
- test/test_synchronous.py
The `Landscape` class provides an abstraction that allows for efficient caching of quantities computed over an attractor landscape. Many useful computations require traversal over the state transition graph of a network. The convenient thing is that we can compute most of these quantities simultaneously, only traversing the graph once.
In this implementation, the computation of quantities such as `attractors` and `in_degree` are all postponed until they are requested. When any one is desired, all of them are computed and cached. This means that subsequent requests, rather than having a computational complexity `O(N)`<sup>1.</sup>, have complexity `O(1)`.
A key feature of our implementation is that `Landscape` is a subclass of `StateSpace`. In other words, we think of a `Landscape` as a …
> The Landscape Class

- neet/boolean/randomnet.py
Three updates to logic network randomization:
1) Add randomization that fixes the mean degree (equivalent to fixing the total number of edges)
2) Change names of randomizations.  Old "fixed" is now "fixed-structure", old "shuffled" is now "fixed-in-degree", and new type is "fixed-mean-degree"
3) Add argument to set random seed (not yet complete)
We still need to add unit tests.
> In progress: Updates to logic network randomization

- neet/boolean/logicnetwork.py
- test/test_logic.py
I implemented a function `is_dependent` for determining whether an input of a node in the truth table is a true connection, ie whether it has logic effect to the node. Another function `reduce_table` is for removing those 'false connections'. Also added is argument `reduced` for the `LogicNetwork`.
> Add functions to treat logic 'connections' that bear no influence

- neet/automata/eca.py
- neet/boolean/logicnetwork.py
- neet/boolean/randomnet.py
- neet/boolean/wtnetwork.py
- neet/interfaces.py
- test/test_boolean.py
- test/test_eca.py
- test/test_interfaces.py
- test/test_logic.py
Removed the ability to return the neighborhood of all nodes. Promoted functions that return incoming neighbors and that return outgoing neighbors to public. These functions may be called frequently, so direct calling is preferable. They are also renamed to `neighbors_in` and `neighbors_out` respectably to make them consistent and more easily discovered through "tab" completion by user.
The ability to sort out `"in"`, `"out"` and `"both"` directions in the original class methods `neighbors` has been moved to the universal function `neighbors` in the `interface` module for less demanding usage.
> Changes to the design of `neighbors` series functions

- neet/boolean/logicnetwork.py
- neet/python3.py
- neet/statespace.py
- test/test_asynchronous.py
- test/test_statespace.py
In computing sensitivity, for example, on large networks (greater than 63 nodes), we were seeing overflow of the `int` type. This isn't typically an issue in python because that usually results in the type switching to `long`. However, since we are using numpy liberally, the resulting overflows were sometimes being converted into `numpy.float64`. This breaks the update methods, such as `LogicNetwork.update` which use bitwise operators under the assumption that everything is an integer.
The solution is to always have `StateSpace.encode` return an integer of type `long`. A clean and simple solution with only a small (~6%) performance hit for small networks.
This closes #92.
> Use long type for encoded states

- neet/boolean/conv.py
- neet/boolean/randomnet.py
- test/test_randomnet.py
The number of states to pick should have been `2**n * p`, where `n` is the width of each binary condition and `p` is the bias. Before this change, it was implemented as `n * p`.
> Fix an algorithmic mistake in `random_binary_conditions`

- neet/boolean/logicnetwork.py
- test/test_logic.py
For large networks, greater than 64 nodes, the state encodings needed for the `LogicNetwork._encoded_network` overflow when a fixed size integer type, e.g. `np.int64` is provided as an index.
This is resolved by explicitly converting the indicies to arbitrary precision integer types.
> Bug Fix #104

- neet/boolean/logicnetwork.py
- neet/sensitivity.py
After a short profiling session, we noticed that the sensitivity function was (ultimately) calling the `StateSpace.__contains__` method significantly more often than expected. We realized that we were using `LogicNetwork.update` in tight loops where we could have been using `LogicNetwork._unsafe_update`. A bit more digging uncovered that the `LogicNetwork._unsafe_update` function was using `StateSpace.encode` when it could have used `StateSpace._unsafe_encode`.
After making these minor changes we gain a ~2.5x runtime improvement. We employed the new version to compute the sensitivity for all 69 biological networks in the GRN Survey: the result was a reduction in runtime from 392 seconds to 153 seconds.
> Improve sensitivity performance

- neet/synchronous.py
- test/test_synchronous.py
We've now removed generators from `neet.synchronous` as per #83. The `StateSpace` class is still a generator since we seldom need a list of the states.
This commit closes #83.
> Generators are Dead

- neet/boolean/wtnetwork.py
- neet/statespace.py
- neet/synchronous.py
- test/test_synchronous.py
Addresses #81, and also clarifies improves some method documentation in the classes: `WTNetwork` and `Statespace` (towards #70)
> Propogate pinning through landscape class

- neet/boolean/eca.py
- neet/boolean/network.py
- neet/network.py
- neet/statespace.py
- neet/synchronous.py
- test/test_statespace.py
This pull request introduces two new classes which (ultimately) derive from `neet.statespace.StateSpace`:
1. `neet.statespace.UniformSpace` - a state space with the same base in each dimension
2. `neet.statespace.BooleanSpace` - a state space with base-2 dimensions
This allows for slightly better performance. More importantly, it allows for smaller, clearer implementations of the various `StateSpace` methods that had already been implemented. Each subclass overrides the general methods in `StateSpace` to provide more specific implementations.
This closes #136 .
> Introduce a hierarchy of state space classes

- neet/sensitivity.py
- neet/statespace.py
- test/test_statespace.py
This pull request removes the `_fast_encode` function and moves `_states_limited` to the `BooleanSpace.subspace` method.
> Start moving sensitivity functions to BooleanNetwork methods

- neet/boolean/sensitivity.py
Several of the sensitivity methods update states, but then only consider a single index. That's a lot of wasted computation for no reason. Providing the `index` argument only updates that single index.
> Use index argument for _unsafe_update

- .gitignore
- examples/basic-examples.ipynb
- neet/boolean/network.py
- neet/network.py
- neet/synchronous.py
After a lot of tinkering around, there just isn't a better way to visualize landscapes than what we were already doing for the networks themselves. Unfortunately no pure python packages exist which are good at this, so we continue to lean on graphviz+pygraphviz.
Would be nice to add some built in visualizations for highlighting attractor states or particular paths, but these can still be accomplished manually by the user.
This will have to be modified slightly once we update to the `Landscape` class to be `LandscapeMixin`.
Addresses #128
> basic landscape visualization

- neet/boolean/eca.py
- neet/boolean/reca.py
- neet/network.py
- neet/synchronous.py
- test/test_synchronous.py
This pull request does the following:
* It removes any reference to `LandscapeMixin` internal variables from `Network`
* Creates the `LandscapeMixin.landscape_data` property
* Add basin entropy to `LandscapeData`
* Renames `LandscapeMixin.__expound` to `LandscapeMixin.expound`
* Creates the `clear_landscape` method (which resets the internal landscape data)
* Calls `clear_landscape` in the `ECA` and `RewiredECA` property setters
* Improves test coverage a smidge
> Extend the LandscapeMixin

- CHANGELOG.md
- neet/network.py
- test/boolean/test_logic.py
- test/boolean/test_wtnetwork.py
Networks were losing lone nodes when convert the network `networkx.DiGraph`. This was fixed by explicitly adding all nodes to the network before adding edges. The reason this was necessary is the `networkx.DiGraph` initializer only adds endpoint nodes when you construct it with a list of edges. Since lone nodes have no edges, they were not included.
Fixes #194
expected)
Please describe the tests that you ran to verify your changes.
We have not tested this for `WTNetwork` on account of #193.
> Resolve #194
